# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(528, 508)
        self.lineNombre = QtWidgets.QLineEdit(Dialog)
        self.lineNombre.setGeometry(QtCore.QRect(150, 60, 201, 41))
        self.lineNombre.setObjectName("lineNombre")
        self.lineContacto = QtWidgets.QLineEdit(Dialog)
        self.lineContacto.setGeometry(QtCore.QRect(150, 130, 201, 41))
        self.lineContacto.setObjectName("lineContacto")
        self.labelProveedor = QtWidgets.QLabel(Dialog)
        self.labelProveedor.setGeometry(QtCore.QRect(150, 40, 47, 13))
        self.labelProveedor.setObjectName("labelProveedor")
        self.labelContacto = QtWidgets.QLabel(Dialog)
        self.labelContacto.setGeometry(QtCore.QRect(150, 110, 47, 13))
        self.labelContacto.setObjectName("labelContacto")
        self.btnGuardar = QtWidgets.QPushButton(Dialog)
        self.btnGuardar.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.btnGuardar.setObjectName("btnGuardar")
        self.lineContacto2 = QtWidgets.QLineEdit(Dialog)
        self.lineContacto2.setGeometry(QtCore.QRect(150, 370, 201, 41))
        self.lineContacto2.setObjectName("lineContacto2")
        self.labelProveedor1 = QtWidgets.QLabel(Dialog)
        self.labelProveedor1.setGeometry(QtCore.QRect(150, 280, 47, 13))
        self.labelProveedor1.setObjectName("labelProveedor1")
        self.labelContacto1 = QtWidgets.QLabel(Dialog)
        self.labelContacto1.setGeometry(QtCore.QRect(150, 350, 47, 13))
        self.labelContacto1.setObjectName("labelContacto1")
        self.lineNombre2 = QtWidgets.QLineEdit(Dialog)
        self.lineNombre2.setGeometry(QtCore.QRect(150, 300, 201, 41))
        self.lineNombre2.setObjectName("lineNombre2")
        self.btnAnterior = QtWidgets.QPushButton(Dialog)
        self.btnAnterior.setGeometry(QtCore.QRect(150, 430, 75, 23))
        self.btnAnterior.setObjectName("btnAnterior")
        self.btnSiguiente = QtWidgets.QPushButton(Dialog)
        self.btnSiguiente.setGeometry(QtCore.QRect(270, 430, 75, 23))
        self.btnSiguiente.setObjectName("btnSiguiente")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 250, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelProveedor.setText(_translate("Dialog", "Nombre:"))
        self.labelContacto.setText(_translate("Dialog", "Contacto:"))
        self.btnGuardar.setText(_translate("Dialog", "Guardar"))
        self.labelProveedor1.setText(_translate("Dialog", "Nombre:"))
        self.labelContacto1.setText(_translate("Dialog", "Contacto:"))
        self.btnAnterior.setText(_translate("Dialog", "Anterior"))
        self.btnSiguiente.setText(_translate("Dialog", "Siguiente"))
        self.label.setText(_translate("Dialog", "Proveedores:"))
        self.label_2.setText(_translate("Dialog", "Ingresar Datos:"))
