# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temporizador.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(20, 70, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeEdit.setFont(font)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnEmpezar = QtWidgets.QPushButton(Dialog)
        self.btnEmpezar.setGeometry(QtCore.QRect(250, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnEmpezar.setFont(font)
        self.btnEmpezar.setObjectName("btnEmpezar")
        self.lcdTiempo = QtWidgets.QLCDNumber(Dialog)
        self.lcdTiempo.setGeometry(QtCore.QRect(110, 170, 181, 61))
        self.lcdTiempo.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdTiempo.setObjectName("lcdTiempo")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.timeEdit.setDisplayFormat(_translate("Dialog", "hh:mm:ss"))
        self.label.setText(_translate("Dialog", "TEMPORIZADOR"))
        self.btnEmpezar.setText(_translate("Dialog", "Empezar"))
        self.label_2.setText(_translate("Dialog", "Seleccionar el tiempo:"))
