# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 223)
        self.btnGenerar = QtWidgets.QPushButton(Dialog)
        self.btnGenerar.setGeometry(QtCore.QRect(140, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnGenerar.setFont(font)
        self.btnGenerar.setObjectName("btnGenerar")
        self.lineC = QtWidgets.QLineEdit(Dialog)
        self.lineC.setGeometry(QtCore.QRect(60, 60, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineC.setFont(font)
        self.lineC.setObjectName("lineC")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Generador de Contraseñas"))
        self.btnGenerar.setText(_translate("Dialog", "Generar"))
