# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.btnSaludar = QtWidgets.QPushButton(Dialog)
        self.btnSaludar.setEnabled(True)
        self.btnSaludar.setGeometry(QtCore.QRect(150, 160, 75, 23))
        self.btnSaludar.setObjectName("btnSaludar")
        self.lineNombre = QtWidgets.QLineEdit(Dialog)
        self.lineNombre.setGeometry(QtCore.QRect(70, 70, 251, 51))
        self.lineNombre.setAutoFillBackground(False)
        self.lineNombre.setInputMask("")
        self.lineNombre.setFrame(False)
        self.lineNombre.setDragEnabled(False)
        self.lineNombre.setReadOnly(False)
        self.lineNombre.setClearButtonEnabled(False)
        self.lineNombre.setObjectName("lineNombre")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnSaludar.setText(_translate("Dialog", "Saludar"))
